### ISSUE TITLE
Publish to nixpkgs

### ISSUE THREAD

**Issue by ifd3f** [ifd3f/caligula#100]
# Is your feature request related to a problem? Please describe.
I'm always frustrated when can't pkgs.caligula

# Describe the solution you'd like
put caligula in nixpkgs

# Describe alternatives you've considered
flake which is annoying

# Additional context
no

**Comment by ifd3f** [comment]
There is a PR to do this right now by @sodiboo https://github.com/NixOS/nixpkgs/pull/310023

**Comment by sodiboo** [comment]
It's been merged into nixpkgs now.

- https://github.com/NixOS/nixpkgs/pull/310023

It's also been merged into  `nixos-unstable` ([PR tracker](https://nixpk.gs/pr-tracker.html?pr=310023)), so you can use it from your NixOS configuration at this moment.
