### ISSUE TITLE
Freezes after finished

### ISSUE THREAD

**Issue by felixonmars** [ifd3f/caligula#107]
## Describe the bug
caligula's TUI always freezes after showing "Done". I tried a lot of different keys and also searched through the bug tracker, but didn't find a way to exit it normally.

Ctrl-C will kill the TUI successfully, but leaving the terminal in a non-operational state (no char output on key input) that could only be fixed by something like "reset".

### Expected behavior
Press any key, or some easily expected keys (Esc, q, Enter...) to exit and prompt it.

## OS/Environment
 - OS: Arch Linux
 - Version: 0.4.4
 - Distribution channel: distribution package

**Comment by ifd3f** [comment]
Yeah, I definitely should also add in a more explicit "press this key to exit" kind of message.

**Comment by ifd3f** [comment]
@felixonmars Okay so I currently have a patch to improve the quit message, but I haven't been able to repro the broken char output thing. What terminal emulator do you use?

**Comment by felixonmars** [comment]
I use tmux inside Gnome Console. It's 100% reproducible here.

**Comment by ifd3f** [comment]
I tried running on tmux inside Gnome Console 46.0 through NixOS, with both v0.4.4 and v0.4.5, and still couldn't reproduce. I'm really not sure what else I could try to reproduce it, but I'm still open to ideas. Maybe try running with `tmux -vv` to log everything caligula and your shell outputs? Barring that, I don't really know what else to try.

**Comment by felixonmars** [comment]
After many attempts to reproduce, I think it only reproduces after escalating using sudo.

A simple test case that reproduces even without tmux:

```
$ touch /tmp/test.img
$ chmod 000 /tmp/test.img
$ caligula burn c906-2024-04-07-10-27-232f22.img -o /tmp/test.img
Input file: c906-2024-04-07-10-27-232f22.img
Detected compression format: no compression
> Is this okay? Yes
? What is the file's hash? <canceled>
Input: c906-2024-04-07-10-27-232f22.img
  Size: 960.5 MB
  Compression: no compression

Output: /tmp/test.img
  Model: [unknown model]
  Size: [unknown size]
  Type: file
  Path: /tmp/test.img
  Removable: unknown

> Is this okay? Yes
> We don't have permissions on /tmp/test.img. Escalate using sudo? Yes
An unexpected error occurred: panicked at src/ui/main.rs:36:9:
                                                              Explicit failure signaled: Some(PermissionDenied)

                               Please report bugs to https://github.com/ifd3f/caligula/issues and attach the following log files, if they exist:
                                                                - /tmp/caligula/log/1715147220378.main.log
                          - /tmp/caligula/log/1715147220378.child.log
                                                                     felix@flygon ~/downloads {101}$ 
```

**Comment by ifd3f** [comment]
Ohh, okay, that would actually make a lot of sense, I was able to reproduce that.

**Comment by ifd3f** [comment]
I ended up mitigating the issue by storing termios data and restoring it after the end of the program. I think this should be good enough? Check the test plan of #122 for what it looks like now.
