### ISSUE TITLE
Support for Zstandard compression

### ISSUE THREAD

**Issue by hacker1024** [ifd3f/caligula#117]
## Is your feature request related to a problem? Please describe.

[Zstandard](http://facebook.github.io/zstd) is an increasingly popular compression format. NixOS, for example, uses it by default when creating SD card images for Raspberry Pis.

## Describe the solution you'd like

It'd be great if this tool supported `.zst` files as it does all other compressed files.

## Describe alternatives you've considered

Can stdin be used? If so, that's a less-fancy workaround.

**Comment by ifd3f** [comment]
Good idea, I can add that
