### ISSUE TITLE
`caligula-bin` AUR package has incorrect version/checksum

### ISSUE THREAD

**Issue by NullCub3** [ifd3f/caligula#118]
## Describe the bug
The `caligula-bin` AUR package is currently set to download caligula version 0.4.4, but has the checksum from 0.4.5, causing the validity check to fail the install.

## OS/Environment
 - Terminal emulator: Alacritty
 - OS: Arch Linux
 - Version: 0.4.5 (0.4.4??)
 - Distribution channel: AUR
 
 ## Additional context
 Not a big deal considering you can get 0.4.5 with the new `extra/caligula` package, very cool btw!

**Comment by ifd3f** [comment]
I wonder if I should just get rid of caligula-bin if we already have caligula in archpkgs.

**Comment by NullCub3** [comment]
Yeah that's probably best to be honest. I know there's a way to set the package to be replaced by the new one ("replaces"?) so that it'll auto install when people update, but that's probably something that the Arch repo maintainers would have to do

**Comment by ifd3f** [comment]
@NullCub3 I think I fixed the issue. Do you want to check? I don't have an arch install lol

**Comment by NullCub3** [comment]
Sorry for the late response, but that solved the issue, thanks!

[Link to relevant AUR commit](https://aur.archlinux.org/cgit/aur.git/commit/?h=caligula-bin&id=dd8352d5a836d8ad35e1325853b8ffb1b482de36)
