### ISSUE TITLE
error[E0277]: the trait bound `valuable::Value<'_>: tracing::Value` is not satisfied

### ISSUE THREAD

**Issue by cinderbdt** [ifd3f/caligula#141]
## Describe the bug
  Compiling bytesize v1.3.0
error[E0277]: the trait bound `valuable::Value<'_>: tracing::Value` is not satisfied
  --> /home/ubuntu-mate/.cargo/registry/src/index.crates.io-6f17d22bba15001f/caligula-0.4.7/src/escalated_daemon/mod.rs:54:9
   |
54 |         info!(msg = msg.as_value(), "Received SpawnWriter request");
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `tracing::Value` is not implemented for `valuable::Value<'_>`
   |
   = help: the following other types implement trait `tracing::Value`:
             bool
             isize
             i8
             i16
             i32
             i64
             i128
             usize
           and 34 others
   = note: required for the cast from `&valuable::Value<'_>` to `&dyn tracing::Value`
   = note: this error originates in the macro `$crate::valueset` which comes from the expansion of the macro `info` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `valuable::Value<'_>: tracing::Value` is not satisfied
   --> /home/ubuntu-mate/.cargo/registry/src/index.crates.io-6f17d22bba15001f/caligula-0.4.7/src/ui/herder/herder.rs:109:9
    |
109 | /         debug!(
110 | |             first_msg = first_msg.as_value(),
111 | |             "Read raw result from child"
112 | |         );
    | |_________^ the trait `tracing::Value` is not implemented for `valuable::Value<'_>`
    |
    = help: the following other types implement trait `tracing::Value`:
              bool
              isize
              i8
              i16
              i32
              i64
              i128
              usize
            and 34 others
    = note: required for the cast from `&valuable::Value<'_>` to `&dyn tracing::Value`
    = note: this error originates in the macro `$crate::valueset` which comes from the expansion of the macro `debug` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `valuable::Value<'_>: tracing::Value` is not satisfied
  --> /home/ubuntu-mate/.cargo/registry/src/index.crates.io-6f17d22bba15001f/caligula-0.4.7/src/childproc_common.rs:34:5
   |
34 | /     info!(
35 | |         ?socket_path,
36 | |         args = args.as_value(),
37 | |         "We are in child process mode"
38 | |     );
   | |_____^ the trait `tracing::Value` is not implemented for `valuable::Value<'_>`
   |
   = help: the following other types implement trait `tracing::Value`:
             bool
             isize
             i8
             i16
             i32
             i64
             i128
             usize
           and 34 others
   = note: required for the cast from `&valuable::Value<'_>` to `&dyn tracing::Value`
   = note: this error originates in the macro `$crate::valueset` which comes from the expansion of the macro `info` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `caligula` (bin "caligula") due to 6 previous errors
error: failed to compile `caligula v0.4.7`, intermediate artifacts can be found at `/tmp/cargo-installLtgEm5`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
ubuntu-mate@ubuntu-mate:~$ 

### To Reproduce
1. boot to Ubuntu Mate live USB
2. apt-get upgrade && apt-get dist-upgrade && apt-get install cargo
3. cargo install caligula

### Log files
Please upload log files to aid in debugging the issue.

## OS/Environment
 - Terminal emulator: MATE Terminal 1.26.1 powered by Virtual TErminal 0.76.0
 - OS: Linux ubuntu-mate 6.8.0-31-generic #&#8203;31-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 00:40:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
 - Version: cargo 1.75.0, caligula v0.4.7, rustc 1.75.0 (82e1608df 2023-12-21) (built from a source tarball)
 - Distribution channel: cargo

## Additional context
ubuntu-mate@ubuntu-mate:~$ ls /tmp/cargo-installLtgEm5/release/deps/libbytesi*
/tmp/cargo-installLtgEm5/release/deps/libbytesize-888f1ee174381d35.rlib
/tmp/cargo-installLtgEm5/release/deps/libbytesize-888f1ee174381d35.rmeta

**Comment by cinderbdt** [comment]
Well, I thought I had made a reproducible minimal test case, but today I got a different result.  I tried the command line RUST_LOG=debug cargo install caligula, and the error happened after the line for base64 instead of bytesize, but the part of the source code where the tracing::Value error appeared is the same.  No "debug" lines were printed in the output, so I'm not sure whether that was useful.  I'm very new to rust.

   Compiling base64 v0.22.1
error[E0277]: the trait bound `valuable::Value<'_>: tracing::Value` is not satisfied
  --> /home/ubuntu-mate/.cargo/registry/src/index.crates.io-6f17d22bba15001f/caligula-0.4.7/src/escalated_daemon/mod.rs:54:9
   |
54 |         info!(msg = msg.as_value(), "Received SpawnWriter request");
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `tracing::Value` is not implemented for `valuable::Value<'_>`
   |
   = help: the following other types implement trait `tracing::Value`:
             bool
             isize
             i8
             i16
             i32
             i64
             i128
             usize
           and 34 others
   = note: required for the cast from `&valuable::Value<'_>` to `&dyn tracing::Value`
   = note: this error originates in the macro `$crate::valueset` which comes from the expansion of the macro `info` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `valuable::Value<'_>: tracing::Value` is not satisfied
   --> /home/ubuntu-mate/.cargo/registry/src/index.crates.io-6f17d22bba15001f/caligula-0.4.7/src/ui/herder/herder.rs:109:9
    |
109 | /         debug!(
110 | |             first_msg = first_msg.as_value(),
111 | |             "Read raw result from child"
112 | |         );
    | |_________^ the trait `tracing::Value` is not implemented for `valuable::Value<'_>`
    |
    = help: the following other types implement trait `tracing::Value`:
              bool
              isize
              i8
              i16
              i32
              i64
              i128
              usize
            and 34 others
    = note: required for the cast from `&valuable::Value<'_>` to `&dyn tracing::Value`
    = note: this error originates in the macro `$crate::valueset` which comes from the expansion of the macro `debug` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `valuable::Value<'_>: tracing::Value` is not satisfied
  --> /home/ubuntu-mate/.cargo/registry/src/index.crates.io-6f17d22bba15001f/caligula-0.4.7/src/childproc_common.rs:34:5
   |
34 | /     info!(
35 | |         ?socket_path,
36 | |         args = args.as_value(),
37 | |         "We are in child process mode"
38 | |     );
   | |_____^ the trait `tracing::Value` is not implemented for `valuable::Value<'_>`
   |
   = help: the following other types implement trait `tracing::Value`:
             bool
             isize
             i8
             i16
             i32
             i64
             i128
             usize
           and 34 others
   = note: required for the cast from `&valuable::Value<'_>` to `&dyn tracing::Value`
   = note: this error originates in the macro `$crate::valueset` which comes from the expansion of the macro `info` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `caligula` (bin "caligula") due to 6 previous errors
error: failed to compile `caligula v0.4.7`, intermediate artifacts can be found at `/tmp/cargo-installDvXwx8`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
ubuntu-mate@ubuntu-mate:~$ 

I'm not understanding what to do next to solve this problem. Any suggestions welcome. Thank you.

**Comment by cinderbdt** [comment]
I've now tried this on Ubuntu Jammy as well. It seems that this is happening in the same source files, and the exact compilation step that is showing in the cargo workflow is not very relevant.  I'm changing the title of this to reflect the trait bound error, hoping that this will be closer to the real issue.

   Compiling shell-words v1.1.0
error[E0277]: the trait bound `valuable::Value<'_>: tracing::Value` is not satisfied
  --> /home/bryan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/caligula-0.4.7/src/escalated_daemon/mod.rs:54:9
   |
54 |         info!(msg = msg.as_value(), "Received SpawnWriter request");
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `tracing::Value` is not implemented for `valuable::Value<'_>`
   |
   = help: the following other types implement trait `tracing::Value`:
             bool
             isize
             i8
             i16
             i32
             i64
             i128
             usize
           and 34 others
   = note: required for the cast from `&valuable::Value<'_>` to `&dyn tracing::Value`
   = note: this error originates in the macro `$crate::valueset` which comes from the expansion of the macro `info` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `valuable::Value<'_>: tracing::Value` is not satisfied
   --> /home/bryan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/caligula-0.4.7/src/ui/herder/herder.rs:109:9
    |
109 | /         debug!(
110 | |             first_msg = first_msg.as_value(),
111 | |             "Read raw result from child"
112 | |         );
    | |_________^ the trait `tracing::Value` is not implemented for `valuable::Value<'_>`
    |
    = help: the following other types implement trait `tracing::Value`:
              bool
              isize
              i8
              i16
              i32
              i64
              i128
              usize
            and 34 others
    = note: required for the cast from `&valuable::Value<'_>` to `&dyn tracing::Value`
    = note: this error originates in the macro `$crate::valueset` which comes from the expansion of the macro `debug` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `valuable::Value<'_>: tracing::Value` is not satisfied
  --> /home/bryan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/caligula-0.4.7/src/childproc_common.rs:34:5
   |
34 | /     info!(
35 | |         ?socket_path,
36 | |         args = args.as_value(),
37 | |         "We are in child process mode"
38 | |     );
   | |_____^ the trait `tracing::Value` is not implemented for `valuable::Value<'_>`
   |
   = help: the following other types implement trait `tracing::Value`:
             bool
             isize
             i8
             i16
             i32
             i64
             i128
             usize
           and 34 others
   = note: required for the cast from `&valuable::Value<'_>` to `&dyn tracing::Value`
   = note: this error originates in the macro `$crate::valueset` which comes from the expansion of the macro `info` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `caligula` (bin "caligula") due to 6 previous errors
error: failed to compile `caligula v0.4.7`, intermediate artifacts can be found at `/tmp/cargo-installs2FCuo`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

**Comment by nim-ka** [comment]
was able to install using `RUSTFLAGS='--cfg tracing_unstable' cargo install caligula`

**Comment by cinderbdt** [comment]
> was able to install using `RUSTFLAGS='--cfg tracing_unstable' cargo install caligula`

Thank you; this worked for me.

**Comment by ifd3f** [comment]
I'm probably going to get rid of the tracing-valuable thing; I barely use it anyways.
