### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by agersant** [ifd3f/caligula#143]
I just want to say thanks for writing this program. Caligula is the first option that popped up when I searched for an Etcher replacement I could use on NixOS. Everything worked out of the box, the TUI is pretty and I love the rationale in the readme. I have no idea how to use `dd` and I never will 😎. 

Keep up the good work! 🙏

**Comment by ifd3f** [comment]
No problem! It makes me happy to know that people enjoy using the software I made!
