### ISSUE TITLE
MacOS security flags the binary as unsafe on new machines

### ISSUE THREAD

**Issue by ALescoulie** [ifd3f/caligula#16]
After running `chmod +x` on Caligula's binary it MacOS refuses to run it, saying it may be malware.

**Comment by ifd3f** [comment]
If I had to make a guess, I think I'll have to sign my code with Apple somehow. https://developer.apple.com/developer-id/

**Comment by ifd3f** [comment]
Okay, so it seems that to sign the code with an Official Apple Certificate :tm: I'm gonna need to enroll in the Apple Developer Program, which costs $99/yr, which I don't wanna pay lol
