### ISSUE TITLE
Add Arch Linux package

### ISSUE THREAD

**Issue by CPlusPatch** [ifd3f/caligula#37]
Pwease 🥺👉🏻👈🏻

**Comment by CPlusPatch** [comment]
![image](https://user-images.githubusercontent.com/42910258/225205469-242aabcf-42c8-4bab-9136-0a6a9287a478.png)
ew disgusting emojis

**Comment by ifd3f** [comment]
is AUR acceptable? :pleading_face: :pleading_face: :pleading_face:

**Comment by ifd3f** [comment]
Well in any case, [I've published a binary package on the AUR](https://aur.archlinux.org/packages/caligula-bin), hope that's good :3

**Comment by CPlusPatch** [comment]
thank youuu you're the cutest girl
